export interface Project {
  name: string;
  desc: string;
  tech: string[];
  category: string;
  year: string;
  link: string;
}

export const projects: Project[] = [
  {
    name: "Book Your Cut",
    desc: "SaaS platform for managing barber bookings, schedules, and customer appointments.",
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "n8n",
      "Firebase",
      "Playwright",
    ],
    category: "Web",
    year: "2026",
    link: "https://bookyourcut.alfitofebriansyah.blog/",
  },
  {
    name: "Bagi Bareng",
    desc: "SaaS platform to split bills by scanning receipts and auto-calculating shares.",
    tech: [
      "Next.js",
      "TypeScript",
      "Ant Design",
      "Tesseract.js",
      "n8n",
      "OpenAI API",
    ],
    category: "Web",
    year: "2026",
    link: "https://bagibareng.alfitofebriansyah.blog/",
  },
  {
    name: "Calculator",
    desc: "A funny calculator that refuses to give instant answers—because even math needs patience.",
    tech: ["Next.js", "TypeScript", "Pure CSS"],
    category: "Web",
    year: "2026",
    link: "https://calculator.alfitofebriansyah.blog/",
  },
  {
    name: "QR Cute",
    desc: "QR generator that creates clean, customizable codes with a cute touch.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS"],
    category: "Web",
    year: "2026",
    link: "https://qrcute.alfitofebriansyah.blog/",
  },
  {
    name: "The Doors Game",
    desc: "Interactive game inspired by the stardew valley.",
    tech: ["HTML Canvas", "CSS", "Aseprite"],
    category: "Web",
    year: "2025",
    link: "https://thedoors.alfitofebriansyah.blog/",
  },
  {
    name: "Temu Jiwa",
    desc: "Platform for selling customizable digital invitations.",
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Radix UI",
      "Firebase",
      "GSAP",
      "Framer Motion",
      "Cloudinary",
    ],
    category: "Web",
    year: "2025",
    link: "https://temujiwa.alfitofebriansyah.blog/",
  },
  {
    name: "Chicken William",
    desc: "Menu ordering and product showcase for Chicken William restaurant.",
    tech: ["Next.js", "TypeScript", "Next Auth", "Tailwind CSS", "Sanity.io"],
    category: "Web",
    year: "2023",
    link: "https://chickenwilliam.alfitofebriansyah.blog/",
  },
  {
    name: "Kokumi Drink",
    desc: "Visually engaging product website for Kokumi brand.",
    tech: ["Next.js", "Tailwind CSS", "Headless UI", "RainbowKit"],
    category: "Web",
    year: "2023",
    link: "https://kokumidrink.alfitofebriansyah.blog/",
  },
  {
    name: "E-Learning Course App",
    desc: "Mobile app for buying and studying online courses.",
    tech: ["Flutter", "Dart"],
    category: "Mobile",
    year: "2023",
    link: "https://github.com/alfitof/aplikasi-elearning-kelompok2",
  },
  {
    name: "Rudi Russel Profile",
    desc: "Company profile website introducing Rudi Russell to the public.",
    tech: ["Next.js", "Tailwind CSS"],
    category: "Web",
    year: "2023",
    link: "https://www.rudirussel-akademie.com/",
  },
  {
    name: "LMS Rudi Russel",
    desc: "Comprehensive e-learning platform with interactive interfaces.",
    tech: ["Next.js", "Tailwind CSS", "Firebase"],
    category: "Web",
    year: "2023",
    link: "https://db-rudirussel.vercel.app/",
  },
  {
    name: "ASE Laboratory Website",
    desc: "Showcase website for Advanced Software Engineer Laboratory activities.",
    tech: ["React", "Tailwind CSS"],
    category: "Web",
    year: "2022",
    link: "https://ase-lab.vercel.app/",
  },
  {
    name: "UMKM Mie Aceh Website",
    desc: "E-commerce platform helping UMKM traders sell their products online.",
    tech: ["MongoDB", "Express.js", "SCSS", "Node.js"],
    category: "Web",
    year: "2022",
    link: "https://github.com/alfitof/umkm-web-mieAceh",
  },
  {
    name: "Droozle Store Website",
    desc: "Product display platform helping sellers showcase their items.",
    tech: ["PHP", "CodeIgniter", "Bootstrap"],
    category: "Web",
    year: "2022",
    link: "https://droozle.netlify.app/",
  },
  {
    name: "KliniQ App Design",
    desc: "App design for accessing doctors, pharmacies, and health insurance easily.",
    tech: ["Figma"],
    category: "Design",
    year: "2022",
    link: "https://www.figma.com/proto/3iLspw3IrqBkjEfkM0kwUK/KliniQ-(Tim-Restu-Ibu)?node-id=26%3A80&scaling=scale-down&page-id=0%3A1&starting-point-node-id=26%3A80",
  },
];
